name: groovkin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  rename: ^2.1.1
  carousel_slider: ^5.0.0
  simple_gradient_text: ^1.3.0
  dotted_border: ^2.1.0
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_credit_card:
    path: ../groovkin/plugin/flutter_credit_card-master
  permission_handler: ^11.3.1
  get_storage: ^2.1.1
  flutter_app_badge: ^2.0.2
  bottom_bar_matu:
    path: ../groovkin/plugin/bottom_bar_matu-master
  date_field: ^6.0.3+1
  flutter_staggered_grid_view: ^0.7.0
  scrollable_clean_calendar: ^1.5.0
  mailer: ^6.1.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  flutter_rating_bar: ^4.0.1
  double_back_to_close_app: ^2.1.0
  flutter_local_notifications: ^17.2.1+2
  firebase_core: ^3.13.0
  map_location_picker:
    path: ../groovkin/plugin/map_location_picker-master
  intl: ^0.19.0
  intl_phone_number_input:
    path: ../groovkin/plugin/intl_phone_number_input-develop
  flutter_datetime_picker_bdaya: ^3.0.2
  month_year_picker: ^0.4.0+1
  image_picker: ^1.1.2
  image_cropper: ^8.0.0
  popup_banner: ^1.0.0
  flutter_chip_tags: ^2.0.2
  dio: ^5.5.0+1
  bot_toast: ^4.1.3
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.3.2
  flutter_spinkit: ^5.2.1
  file_picker: ^8.0.6
  http_parser: ^4.1.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.3
  wakelock_plus: ^1.1.4
  iconsax: ^0.0.8
  http: ^1.2.1
  collection: ^1.19.0
  datetime_picker_formfield_new: ^2.1.0
  image_cropper_platform_interface: ^7.0.0  
  form_builder_extra_fields: ^10.2.0
  better_player_plus: 1.0.6
  in_app_purchase: ^3.2.1
  purchases_flutter: ^8.6.1
  webview_flutter: ^4.4.2
  app_settings: ^5.1.1
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  otp_text_field:
    path: ../groovkin/plugin/OTPTextField-dev
  country_state_city_pro:
    path: ../groovkin/plugin/Country-State-City-Picker-Pro-master
  flutter_layout_grid: ^2.0.7
  custom_pop_up_menu: ^1.2.4
  sticky_grouped_list: ^3.1.0
  sqflite: ^2.4.1
  socket_io_client: ^3.0.2
  swipe_to: ^1.0.6
  syncfusion_flutter_charts: ^28.2.7
  fl_chart: ^0.70.2
  material_charts: ^0.0.26
  google_fonts: ^6.2.1
  geocoding: ^3.0.0
  firebase_auth: ^5.5.1
  reorderables: ^0.6.0
  firebase_messaging: ^15.2.6
  flutter_web_auth_2: ^4.1.0
  font_awesome_flutter: ^10.9.0
  geolocator: ^9.0.1
  flutter_facebook_auth: ^7.1.2
  syncfusion_flutter_pdfviewer:
  readmore: ^3.0.0
dependency_overrides:
  flutter_datetime_picker_bdaya: ^3.0.2
  collection: ^1.19.0
  image_cropper: ^7.1.0
  http: ^1.2.1
  intl: ^0.19.0
  form_builder_extra_fields: ^10.2.0
  image_cropper_platform_interface: ^6.1.0
  socket_io_client: ^3.0.2
  modal_progress_hud_nsn: ^0.5.1
  web: ^0.5.1
  flutter_widget_from_html_core: 0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/deletedImg/

  fonts:
    - family: poppinsMedium
      fonts:
        - asset: assets/Poppins-Medium.ttf
    - family: poppinsRegular
      fonts:
        - asset: assets/Poppins-Regular.ttf

    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: robotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
