name: groovkin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  get: ^4.7.3
  rename: ^3.1.0
  carousel_slider: ^5.1.2
  simple_gradient_text: ^1.4.0
  dotted_border: ^3.1.0
  sign_in_with_apple: ^8.1.0
  google_sign_in: ^7.2.0
  flutter_credit_card:
    path: plugin/flutter_credit_card-master
  permission_handler: ^12.0.3
  get_storage: ^2.1.1
  flutter_app_badge: ^2.0.2
  bottom_bar_matu:
    path: plugin/bottom_bar_matu-master
  date_field: ^6.0.3+1
  flutter_staggered_grid_view: ^0.7.0
  scrollable_clean_calendar: ^1.5.0
  mailer: ^7.1.0
  pdf: ^3.12.0
  open_file: ^3.5.11
  flutter_rating_bar: ^4.0.1
  double_back_to_close_app: ^2.1.0
  flutter_local_notifications: ^22.0.0
  firebase_core: ^4.10.0
  map_location_picker:
    path: plugin/map_location_picker-master
  intl: ^0.20.2
  intl_phone_number_input:
    path: plugin/intl_phone_number_input-develop
  flutter_datetime_picker_bdaya: ^3.0.2
  month_year_picker: ^0.5.0+1
  image_picker: ^1.2.2
  image_cropper: ^12.2.1
  popup_banner: ^1.0.0
  flutter_chip_tags: ^2.0.2
  dio: ^5.9.2
  bot_toast: ^4.1.3
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.5.5
  flutter_spinkit: ^5.2.2
  file_picker: ^11.0.2
  http_parser: ^4.1.2
  video_thumbnail: ^0.5.6
  path_provider: ^2.1.5
  wakelock_plus: ^1.2.8
  iconsax: ^0.0.8
  http: ^1.6.0
  collection: ^1.19.1
  datetime_picker_formfield_new: ^2.1.0
  image_cropper_platform_interface: ^8.0.0
  form_builder_extra_fields: ^12.2.0
  better_player_plus: ^1.2.1
  in_app_purchase: ^3.3.0
  purchases_flutter: ^10.2.2
  webview_flutter: ^4.13.1
  app_settings: ^7.0.0
  fluttertoast: ^9.1.0
  url_launcher: ^6.3.2
  otp_text_field:
    path: plugin/OTPTextField-dev
  country_state_city_pro:
    path: plugin/Country-State-City-Picker-Pro-master
  flutter_layout_grid: ^2.0.8
  custom_pop_up_menu: ^1.2.4
  sticky_grouped_list: ^3.1.0
  sqflite: ^2.4.3
  socket_io_client: ^3.1.5
  swipe_to: ^1.0.6
  syncfusion_flutter_charts: ^33.2.10
  fl_chart: ^1.2.0
  material_charts: ^0.0.39
  google_fonts: ^8.1.0
  geocoding: ^4.0.0
  firebase_auth: ^6.5.2
  reorderables: ^0.6.0
  firebase_messaging: ^16.3.0
  flutter_web_auth_2: ^5.0.3
  font_awesome_flutter: ^11.0.0
  geolocator: ^14.0.2
  flutter_facebook_auth: ^7.1.7
  syncfusion_flutter_pdfviewer: ^33.2.10
  readmore: ^3.0.0
  pin_code_fields: ^9.4.0
  circular_countdown_timer: ^0.2.4
  pretty_dio_logger: ^1.4.0
dependency_overrides:
  flutter_datetime_picker_bdaya: ^3.0.2
  collection: ^1.19.0
  image_cropper: ^12.2.1
  http: ^1.6.0
  intl: ^0.20.2
  form_builder_extra_fields: ^12.2.0
  image_cropper_platform_interface: ^8.0.0
  socket_io_client: ^3.1.5
  mask_text_input_formatter: ^2.9.0

  modal_progress_hud_nsn: ^0.5.1
  web: ^0.5.1
  flutter_widget_from_html_core: 0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/deletedImg/

  fonts:
    - family: poppinsMedium
      fonts:
        - asset: assets/Poppins-Medium.ttf
    - family: poppinsRegular
      fonts:
        - asset: assets/Poppins-Regular.ttf

    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: robotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
