// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaKVQhEDdDJ2BER0Ut7tTJajxETG0PsXc',
    appId: '1:682228072753:android:cb8de8728eb9544c3f3010',
    messagingSenderId: '682228072753',
    projectId: 'my-groovkin-app',
    storageBucket: 'my-groovkin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuAkWOdbbcjtEe0X4-u0TEbrsvXUdNWXA',
    appId: '1:682228072753:ios:199be50ad42d76973f3010',
    messagingSenderId: '682228072753',
    projectId: 'my-groovkin-app',
    storageBucket: 'my-groovkin-app.firebasestorage.app',
    androidClientId: '682228072753-0thr3a4cgic3g4cg8gc1opl8vud2gu2f.apps.googleusercontent.com',
    iosClientId: '682228072753-gkopa070pgphkcknhl0p1dkjd1vf0ve0.apps.googleusercontent.com',
    iosBundleId: 'com.gologonow.groovkinn',
  );

}